FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore Instyga.Trilhas.csproj
# Build and publish a release
RUN dotnet publish Instyga.Trilhas.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /App
COPY --from=build-env /App/out .
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true  
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 3000
EXPOSE 80


ENTRYPOINT ["dotnet", "Instyga.Trilhas.dll", "--urls", "http://*:80"]